"""LLM-powered domain generation using the Databricks Foundation Model API."""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any

from .config import DEFAULT_LLM_ENDPOINT, LLM_MAX_RETRIES, LLM_MAX_TOKENS, LLM_TEMPERATURE


# ---------------------------------------------------------------------------
# Domain spec dataclasses
# ---------------------------------------------------------------------------


@dataclass
class ColumnSpec:
    name: str
    sql_type: str
    comment: str
    is_dimension: bool
    generation_expr: str


@dataclass
class TableSpec:
    table_name: str
    description: str
    columns: list[ColumnSpec]
    seasonal_patterns: dict
    entity_dimension: str
    dimension_values: list[dict]
    category_distribution: dict


@dataclass
class MetricViewSpec:
    view_name: str
    source_table: str
    dimensions: list[dict]
    measures: list[dict]


@dataclass
class ExampleSQL:
    question: str
    sql_lines: list[str]


@dataclass
class SQLSnippets:
    filters: list[dict]
    expressions: list[dict]
    measures: list[dict]


@dataclass
class BenchmarkSpec:
    question: str
    sql_lines: list[str]


@dataclass
class DomainSpec:
    """Complete domain specification generated by LLM."""

    company_name: str
    industry: str
    use_case: str
    space_title: str
    space_description: str
    schema_basename: str

    tables: list[TableSpec]
    metric_views: list[MetricViewSpec]

    genie_instructions: str
    sample_questions: list[str]
    example_sqls: list[ExampleSQL]
    sql_snippets: SQLSnippets
    benchmarks: list[BenchmarkSpec]


# ---------------------------------------------------------------------------
# LLM prompt
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """\
You are a data modeling expert that generates complete domain specifications for \
Databricks Genie spaces. You produce structured JSON that drives synthetic data \
generation, metric view creation, and Genie space configuration.

You must return ONLY valid JSON matching the schema described in the user message. \
No markdown, no code fences, no explanation — just the JSON object."""

USER_PROMPT_TEMPLATE = """\
Generate a complete domain specification for a Databricks Genie space.

## Business Context
- **Industry:** {industry}
- **Company:** {company_name}
- **Use Case:** {use_case}
- **Context:** {business_context}

## Constraints
- Generate exactly {num_tables} tables
- Generate exactly {num_products} entity items (e.g., products, patients, assets) \
spread across 4-5 categories
- Generate exactly {num_locations} locations/facilities/sites spread across regions
- Each table must have 8-12 columns
- Each table gets one metric view with 4-6 measures
- Generate exactly 7 sample_questions, 7 example_sqls, 7 benchmarks
- SQL snippets: exactly 3 filters, 3 expressions, 4 measures
- At least 2 of the 7 example_sqls must use MEASURE() syntax against metric views
- At least 2 of the 7 benchmarks must use MEASURE() syntax
- All SQL must be Databricks SQL compatible
- Table names must be valid SQL identifiers (lowercase, underscores only)
- The schema_basename must be a short lowercase identifier (no spaces)

## Table Archetypes
The {num_tables} tables should follow these archetypes (adapt names to the domain):
1. **Transaction table** — daily event records (orders, encounters, tickets, etc.). \
entity_dimension = "transaction". Columns should include an ID, date, entity references, \
quantities, amounts, and a status field with 3-4 possible values.
2. **Snapshot table** — periodic status snapshots (inventory levels, bed utilization, \
asset health, etc.). entity_dimension = "snapshot". Taken at weekly intervals.
3. **Forecast table** — predictions vs actuals (demand forecasts, readmission \
predictions, etc.). entity_dimension = "forecast". Monthly granularity with \
model_version field (v3.0, v3.1, v3.2).

## Column Generation Expressions
Each column needs a `generation_expr` — a SQL expression that produces the column \
value from the skeleton CTE. Available variables in expressions:
- `e.<any_entity_field>` — entity dimension columns
- `d.dt` — the date column from the date range
- `{{qty_noise}}` — deterministic random decimal [0,1) for quantities
- `{{status_noise}}` — deterministic random decimal [0,1) for status assignment
- `{{id_seq}}` — deterministic integer 0-499 for ID generation
- `{{seed}}` — the seed integer
- `ROW_NUMBER() OVER (ORDER BY d.dt, e.<pk>)` — for sequential IDs
- `MONTH(d.dt)`, `DAYOFWEEK(d.dt)` — date functions

For columns that come directly from the entity dimension, set generation_expr to \
empty string "" and the system will use `e.<column_name>`.

## Seasonal Patterns Format
seasonal_patterns is a dict where keys are category names and values are dicts \
mapping month numbers (as strings) to selection probabilities. Example:
{{"Electronics": {{"11,12": 0.06, "6,7": 0.015}}, "Food": {{"5,6,7": 0.045}}}}

category_distribution is a dict mapping category names to their default (non-seasonal) \
selection probability. Example:
{{"Electronics": 0.025, "Food": 0.035}}

## SQL in example_sqls and benchmarks
- Use {{fqn}} as a placeholder for the fully-qualified schema name (e.g., catalog.schema)
- SQL should be broken into lines as a list of strings
- MEASURE() queries must reference the metric view name, not the base table
- MEASURE() queries should use GROUP BY ALL

## Few-Shot Example (Demand Forecasting Domain)
Here is a partial example of the expected output for a logistics/supply chain use case:

```json
{{
  "company_name": "NorthStar Logistics",
  "industry": "Logistics",
  "use_case": "Demand forecasting and inventory management",
  "space_title": "Northstar Logistics - Demand Forecasting & Inventory \\ud83d\\ude9b",
  "space_description": "Supply chain analytics for NorthStar Logistics. Ask questions about demand forecasts, inventory levels, stockout risks, fill rates, and shipment trends across 20 products and 8 distribution centers.",
  "schema_basename": "demand_forecasting",
  "tables": [
    {{
      "table_name": "shipment_orders",
      "description": "Daily shipment order history with delivered units, warehouse origins, destination regions, and order outcomes.",
      "columns": [
        {{"name": "order_id", "sql_type": "STRING", "comment": "Unique order identifier", "is_dimension": false, "generation_expr": "CONCAT('ORD-', LPAD(CAST(ROW_NUMBER() OVER (ORDER BY d.dt, e.sku) + 10000 AS STRING), 6, '0'))"}},
        {{"name": "order_date", "sql_type": "DATE", "comment": "Date order was placed", "is_dimension": true, "generation_expr": "d.dt"}},
        {{"name": "product_sku", "sql_type": "STRING", "comment": "Product SKU code", "is_dimension": true, "generation_expr": ""}},
        {{"name": "product_name", "sql_type": "STRING", "comment": "Human-readable product name", "is_dimension": true, "generation_expr": ""}},
        {{"name": "product_category", "sql_type": "STRING", "comment": "Product category", "is_dimension": true, "generation_expr": ""}},
        {{"name": "quantity", "sql_type": "INT", "comment": "Number of units ordered", "is_dimension": false, "generation_expr": "CAST(10 + FLOOR({{qty_noise}} * 100) AS INT)"}},
        {{"name": "unit_price", "sql_type": "DOUBLE", "comment": "Price per unit in USD", "is_dimension": false, "generation_expr": ""}},
        {{"name": "order_status", "sql_type": "STRING", "comment": "Order status: Delivered, Backorder, In Transit, or Cancelled", "is_dimension": true, "generation_expr": "CASE WHEN {{status_noise}} < 0.02 THEN 'Cancelled' WHEN {{status_noise}} < 0.05 THEN 'Backorder' WHEN {{status_noise}} < 0.08 THEN 'In Transit' ELSE 'Delivered' END"}}
      ],
      "seasonal_patterns": {{
        "Electronics": {{"11,12": 0.06}},
        "Clothing & Apparel": {{"3,4,9,10": 0.055}}
      }},
      "entity_dimension": "transaction",
      "dimension_values": [
        {{"sku": "SKU-EL-001", "name": "Wireless Bluetooth Speaker", "category": "Electronics", "price": 49.99}},
        {{"sku": "SKU-EL-003", "name": "USB-C Hub 7-in-1", "category": "Electronics", "price": 39.99}}
      ],
      "category_distribution": {{
        "Electronics": 0.025,
        "Food & Beverage": 0.035,
        "Clothing & Apparel": 0.02
      }}
    }}
  ],
  "metric_views": [
    {{
      "view_name": "shipment_orders_metrics",
      "source_table": "shipment_orders",
      "dimensions": [
        {{"name": "order_date", "expr": "order_date"}},
        {{"name": "product_category", "expr": "product_category"}}
      ],
      "measures": [
        {{"name": "total_revenue", "expr": "SUM(quantity * unit_price) FILTER (WHERE order_status = 'Delivered')", "comment": "Total revenue from delivered orders in USD"}},
        {{"name": "fill_rate", "expr": "COUNT(DISTINCT CASE WHEN order_status = 'Delivered' THEN order_id END) * 100.0 / NULLIF(COUNT(DISTINCT order_id), 0)", "comment": "Percentage of orders that were delivered"}}
      ]
    }}
  ],
  "genie_instructions": "You are a supply chain analytics assistant for NorthStar Logistics...\\nWhen answering aggregation questions, prefer the metric views with MEASURE() syntax.",
  "sample_questions": [
    "Which SKUs are currently below their reorder point?",
    "What is the forecast accuracy by product category?"
  ],
  "example_sqls": [
    {{
      "question": "What is our fill rate by product category?",
      "sql_lines": ["SELECT product_category,\\n", "  MEASURE(fill_rate) AS fill_rate\\n", "FROM {{fqn}}.shipment_orders_metrics\\n", "GROUP BY ALL\\n", "ORDER BY fill_rate ASC"]
    }}
  ],
  "sql_snippets": {{
    "filters": [{{"sql": "orders.order_status = 'Delivered'", "display_name": "delivered orders", "synonyms": ["completed orders"], "instruction": "Use when calculating fill rate."}}],
    "expressions": [{{"alias": "order_month", "sql": "DATE_TRUNC('month', orders.order_date)", "display_name": "month", "synonyms": ["order month"]}}],
    "measures": [{{"alias": "total_revenue", "sql": "SUM(orders.quantity * orders.unit_price)", "display_name": "total revenue", "synonyms": ["revenue", "sales"]}}]
  }},
  "benchmarks": [
    {{
      "question": "What is our fill rate by product category?",
      "sql_lines": ["SELECT product_category,\\n", "  MEASURE(fill_rate) AS fill_rate\\n", "FROM {{fqn}}.shipment_orders_metrics\\n", "GROUP BY ALL\\n", "ORDER BY fill_rate ASC"]
    }}
  ]
}}
```

Now generate the COMPLETE domain specification for the business context above. \
Return ONLY the JSON object — no markdown fences, no commentary."""


# ---------------------------------------------------------------------------
# Generation logic
# ---------------------------------------------------------------------------


def generate_domain_spec(
    spark: Any,
    industry: str,
    company_name: str,
    use_case: str,
    business_context: str,
    num_tables: int = 3,
    num_products: int = 20,
    num_locations: int = 8,
    endpoint: str = DEFAULT_LLM_ENDPOINT,
) -> DomainSpec:
    """Generate a DomainSpec by calling the Foundation Model API."""

    import mlflow.deployments

    client = mlflow.deployments.get_deploy_client("databricks")

    user_prompt = USER_PROMPT_TEMPLATE.format(
        industry=industry,
        company_name=company_name,
        use_case=use_case,
        business_context=business_context,
        num_tables=num_tables,
        num_products=num_products,
        num_locations=num_locations,
    )

    last_error = None
    for attempt in range(1 + LLM_MAX_RETRIES):
        try:
            response = client.predict(
                endpoint=endpoint,
                inputs={
                    "messages": [
                        {"role": "system", "content": SYSTEM_PROMPT},
                        {"role": "user", "content": user_prompt},
                    ],
                    "max_tokens": LLM_MAX_TOKENS,
                    "temperature": LLM_TEMPERATURE,
                },
            )

            content = response["choices"][0]["message"]["content"]
            # Strip markdown fences if present
            content = content.strip()
            if content.startswith("```"):
                content = content.split("\n", 1)[1]
            if content.endswith("```"):
                content = content.rsplit("```", 1)[0]
            content = content.strip()

            raw = json.loads(content)
            spec = _parse_domain_spec(raw)
            _validate_domain_spec(spec, num_tables, num_products, num_locations)
            return spec

        except Exception as exc:
            last_error = exc
            if attempt < LLM_MAX_RETRIES:
                continue

    raise RuntimeError(
        f"Failed to generate domain spec after {1 + LLM_MAX_RETRIES} attempts: {last_error}"
    )


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------


def _parse_domain_spec(raw: dict) -> DomainSpec:
    """Parse a raw JSON dict into a DomainSpec."""

    tables = [_parse_table_spec(t) for t in raw["tables"]]
    metric_views = [_parse_metric_view_spec(mv) for mv in raw["metric_views"]]
    example_sqls = [
        ExampleSQL(question=e["question"], sql_lines=e["sql_lines"])
        for e in raw["example_sqls"]
    ]
    benchmarks = [
        BenchmarkSpec(question=b["question"], sql_lines=b["sql_lines"])
        for b in raw["benchmarks"]
    ]
    snippets_raw = raw["sql_snippets"]
    sql_snippets = SQLSnippets(
        filters=snippets_raw["filters"],
        expressions=snippets_raw["expressions"],
        measures=snippets_raw["measures"],
    )

    return DomainSpec(
        company_name=raw["company_name"],
        industry=raw["industry"],
        use_case=raw["use_case"],
        space_title=raw["space_title"],
        space_description=raw["space_description"],
        schema_basename=raw["schema_basename"],
        tables=tables,
        metric_views=metric_views,
        genie_instructions=raw["genie_instructions"],
        sample_questions=raw["sample_questions"],
        example_sqls=example_sqls,
        sql_snippets=sql_snippets,
        benchmarks=benchmarks,
    )


def _parse_table_spec(raw: dict) -> TableSpec:
    """Parse a raw table dict into a TableSpec."""

    columns = [
        ColumnSpec(
            name=c["name"],
            sql_type=c["sql_type"],
            comment=c["comment"],
            is_dimension=c["is_dimension"],
            generation_expr=c.get("generation_expr", ""),
        )
        for c in raw["columns"]
    ]
    return TableSpec(
        table_name=raw["table_name"],
        description=raw["description"],
        columns=columns,
        seasonal_patterns=raw.get("seasonal_patterns", {}),
        entity_dimension=raw.get("entity_dimension", "transaction"),
        dimension_values=raw.get("dimension_values", []),
        category_distribution=raw.get("category_distribution", {}),
    )


def _parse_metric_view_spec(raw: dict) -> MetricViewSpec:
    """Parse a raw metric view dict into a MetricViewSpec."""

    return MetricViewSpec(
        view_name=raw["view_name"],
        source_table=raw["source_table"],
        dimensions=raw["dimensions"],
        measures=raw["measures"],
    )


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


def _validate_domain_spec(
    spec: DomainSpec,
    expected_tables: int,
    expected_products: int,
    expected_locations: int,
) -> None:
    """Validate that the domain spec meets constraints."""

    if len(spec.tables) != expected_tables:
        raise ValueError(
            f"Expected {expected_tables} tables, got {len(spec.tables)}"
        )

    if len(spec.metric_views) != expected_tables:
        raise ValueError(
            f"Expected {expected_tables} metric views, got {len(spec.metric_views)}"
        )

    if len(spec.sample_questions) != 7:
        raise ValueError(
            f"Expected 7 sample questions, got {len(spec.sample_questions)}"
        )

    if len(spec.example_sqls) != 7:
        raise ValueError(
            f"Expected 7 example SQLs, got {len(spec.example_sqls)}"
        )

    if len(spec.benchmarks) != 7:
        raise ValueError(
            f"Expected 7 benchmarks, got {len(spec.benchmarks)}"
        )

    if len(spec.sql_snippets.filters) != 3:
        raise ValueError(
            f"Expected 3 filters, got {len(spec.sql_snippets.filters)}"
        )

    if len(spec.sql_snippets.expressions) != 3:
        raise ValueError(
            f"Expected 3 expressions, got {len(spec.sql_snippets.expressions)}"
        )

    if len(spec.sql_snippets.measures) != 4:
        raise ValueError(
            f"Expected 4 measures, got {len(spec.sql_snippets.measures)}"
        )

    # Verify at least 2 example SQLs use MEASURE()
    measure_examples = sum(
        1 for ex in spec.example_sqls
        if any("MEASURE(" in line for line in ex.sql_lines)
    )
    if measure_examples < 2:
        raise ValueError(
            f"At least 2 example SQLs must use MEASURE(), found {measure_examples}"
        )

    # Verify at least 2 benchmarks use MEASURE()
    measure_benchmarks = sum(
        1 for b in spec.benchmarks
        if any("MEASURE(" in line for line in b.sql_lines)
    )
    if measure_benchmarks < 2:
        raise ValueError(
            f"At least 2 benchmarks must use MEASURE(), found {measure_benchmarks}"
        )

    for table in spec.tables:
        if not table.columns:
            raise ValueError(f"Table {table.table_name} has no columns")
        if not table.dimension_values:
            raise ValueError(f"Table {table.table_name} has no dimension_values")
